### ISSUE TITLE
学习使用万维网（World Wide Web，WWW）和HTML

### ISSUE THREAD

**Issue by yinheco** [zer4tul/hacker-howto#6]
学习使用万维网（World Wide Web，WWW）和HTML
===>建议修改为
学习使用万维网（World Wide Web，WWW）和编写HTML

**Comment by zer4tul** [comment]
HTML在这里指代的是超文本标记语言，而不是（由HTML编写的）网页。“编写超文本标记语言”给人的感觉是不通的，而“使用超文本标记语言”感觉会好一些。

如果将这段改成

> 学习使用万维网（World Wide Web，WWW）和HTML（超文本标记语言）

这样是否会好一些？

**Comment by yinheco** [comment]
这样顺多啦，也没歧义！
