### ISSUE TITLE
翻译中的错误

### ISSUE THREAD

**Issue by slegetank** [zer4tul/hacker-howto#7]
花了1个小时看完了全文，发现了以下错误。
* 错别字
1. 尊重能力，你就回享受到提高自己的能力所带来的乐趣
   回->会
   -> 尊重能力，你就会享受到提高自己的能力所带来的乐趣
2. 写HTML会交你一些有助于学习的思考习惯。
   交->教
   -> 写HTML会教你一些有助于学习的思考习惯。
3. Linux Torvalds的公开怀疑所阻碍
   Linux->Linus
   -> Linus Torvalds的公开怀疑所阻碍
4. Virsual Basic是一门好的入门语言吗
   Virsual->Visual
   -> Visual Basic是一门好的入门语言吗
5. 你需要做到自我驱动，否则无法进步。这也是为什么让别人帮你挑选反向几乎都不会有用。
   反->方
   -> 你需要做到自我驱动，否则无法进步。这也是为什么让别人帮你挑选方向几乎都不会有用。
6. 黑客节最受尊敬的圣人是那些编写了大型的
   节->间（不确定）
   -> 黑客间最受尊敬的圣人是那些编写了大型的
7. 我该从哪种语言开始学？]
   ]->删掉
   -> 我该从哪种语言开始学？
* 链接
1. [Computer Science Circles][#Computer Science Circles]
2. [历史记录：黑客活动，开源，和自由软件][#历史记录：黑客活动，开源，和自由软件]
3. [LDP][#LDP]
* 词句修改
1. 直到你的作品达到如你在范文中所见的简洁和力量。
   力量->强大
   -> 直到你的作品达到如你在范文中所见的简洁和强大。
2. 注意，相比Ubuntu的默认那个丑陋的几乎不可用的“Unity”桌面，Xubuntu和Kubuntu更好用一点。
   相比Ubuntu的默认->相比Ubuntu默认的
   -> 注意，相比Ubuntu默认的那个丑陋的几乎不可用的“Unity”桌面，Xubuntu和Kubuntu更好用一点。
3. 这看上去跟普通人没太大直接关系
   太大直接->没太大关系
   -> 这看上去跟普通人没太大关系
4. 你是否为了让计算机成为这个世界更富饶、更人性化的工具而努力
   富饶->丰富多彩
   -> 你是否为了让计算机成为这个世界更丰富多彩、更人性化的工具而努力

**Comment by zer4tul** [comment]
感谢你的反馈和建议，上述提到的问题已全部修复。
